### ISSUE TITLE
Scala-like multiple-parameter lists for decorator functions with arguments

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-decorators#10]
I wonder if it would be worthwhile to pursue a syntax extension for functions to allow for multiple-parameter lists:

```js
function defineElement(tagName)({ kind, elements }) {
    assert(kind == "class");
    return {
      kind,
      elements,
      // This callback is called once the class is otherwise fully defined
      finisher(klass) {
        window.customElements.define(tagName, klass);
      }
    }
  }
}
```
Probably not now, but perhaps worth considering at a later date if there's enough of a use case.

**Comment by rbuckton** [comment]
Besides, you could just write:

```js
const defineElement = (tagName) => ({ kind, elements }) => {
  ...
};
```

**Comment by littledan** [comment]
Interesting idea. Presumably, though, this would work as a separate proposal, right? Decorators wouldn't need this to land.

**Comment by littledan** [comment]
Let's continue this in a separate proposal. People want currying for other reasons, too.
