### ISSUE TITLE
5.1.2.7 GetPrivateName should return something

### ISSUE THREAD

**Issue by erights** [tc39/proposal-decorators#103]
The currently specified algorithm  does not return anything.

**Comment by ENvironmentSet** [comment]
following the algorithm, seems return `pn`
So, How about change line 3 like blow?

````
3. Return O.[[PrivateNameData]]. 
````

**Comment by littledan** [comment]
@environmentset That fix looks good to me. Would you be interested in making it as a PR?

**Comment by ENvironmentSet** [comment]
@littledan Sure, I will do my best :)
