### ISSUE TITLE
What does "finisher?: (klass): undefined or constructor;" mean?

### ISSUE THREAD

**Issue by erights** [tc39/proposal-decorators#104]

**Comment by littledan** [comment]
This means, the finisher property should be a function which takes a class as a parameter and returns undefined or a constructor. Any idea for how to write this note more clearly?

**Comment by littledan** [comment]
Closing, as this relates to the previous "Stage 2" decorators proposal. See the [current proposal](https://github.com/tc39/proposal-decorators), which does not have this issue.
