### ISSUE TITLE
Need %PrivateNameInit% in addition to %PrivateNameGet% and %PrivateNameSet%

### ISSUE THREAD

**Issue by erights** [tc39/proposal-decorators#106]
Leads to a simpler, more expressive, and more consistent initialization protocol.

attn @caridy

**Comment by littledan** [comment]
PrivateNameInit was a deliberate, stylistic omission--the only way to add private fields is through a field declaration. This encourages developers to use the more optimizable path. @jridgewell has also asked about this feature, but I can't find the issue right now.

**Comment by littledan** [comment]
@erights and I discussed this further at the May 2018 TC39 meeting, and it seemed to me that he was satisfied with this answer (please correct me here if I'm mistaken).
