### ISSUE TITLE
broken link to associated proposal

### ISSUE THREAD

**Issue by ENvironmentSet** [tc39/proposal-decorators#122]
At line 1 of spec document. the link to private method proposal is broken
> This proposal adds decorators to JavaScript. It incorporates features needed to make decorators work with the class fields and [private methods](https://littledan.github.io/proposal-private-methods).

I think this link have to replaced by [private methods](https://tc39.github.io/proposal-private-methods/)

**Comment by littledan** [comment]
Thanks! Great catch. PR?

**Comment by ENvironmentSet** [comment]
yes :)
