### ISSUE TITLE
TC39 sad news

### ISSUE THREAD

**Issue by pabloalmunia** [tc39/proposal-decorators#247]
I have read the [notes](https://github.com/rwaldron/tc39-notes/blob/master/es9/2019-01/jan-30.md#decorators-for-stage-3) of the last TC39 meeting and I have been saddened to see that there is no consensus about decorators proposal.

I can understand that the current proposal has a certain complexity, but at the same time it has great power. Daniel and champion group did a very good work.

We, the developers, should wait for agreement of wise. It's a very sad news.

**Comment by littledan** [comment]
I'm very sorry that it's taking even longer to come to a stable decorators standard. Right now, the best way you all can help is by including your use cases in https://github.com/tc39/proposal-decorators/issues/231 so we can make sure that they are handled in a future proposal.
