### ISSUE TITLE
Decorators and babel polyfills

### ISSUE THREAD

**Issue by pldilley** [tc39/proposal-decorators#255]
It seems that the current babel implementation of decorators relies on using Symbol. However, even with babel polyfills enabled, in this instance Symbol is not polyfilled and an error is thrown in IE11.

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": [
          "ie 11",
          "last 2 versions",
          "> 1%"
        ]
      },
      "modules": false,
      "useBuiltIns": "usage"
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-class-properties"],
    ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": false }],
```

Error resulting in IE11:

>  'Symbol' is undefined

It should be noted that `"useBuiltIns": "usage"` is experimental itself.

Thanks

**Comment by littledan** [comment]
This repository is for the decorators proposal itself, not the Babel implementation. Please file an issue at https://github.com/babel/babel/issues/new instead. cc @nicolo-ribaudo
