### ISSUE TITLE
Static decorators: creating PrivateName in the class decorator

### ISSUE THREAD

**Issue by Lodin** [tc39/proposal-decorators#262]
This issue starts the series of two alternative topics where I would like to discuss class decorators. They are not about MVP, more likely it should be documented in the NEXTBUILTINS as a follow-on proposal.

For now, I see a lot of property-level decorators, but class decorators are still limited with the MVP proposal. However, for a complex project like Corpuscule, we need more tools to allow creating a self-containing system with a lot of properties and methods, private or public.

So there is the first approach I would like to suggest.

## New decorators to create and work with PrivateNames
Let's take a very simplified `@element` decorator from the [`@corpuscule/element`](https://github.com/corpusculejs/corpuscule/tree/master/packages/element) as an example. It defines two symbolic properties, `propertyChangedCallback` (runs when something sets the class property marked with `@property` decorator and in the end launches `$$invalidate`) and `render` (used by `$$invalidate` to render element's content), redefines a `connectedCallback` and adds a private `$$invalidate` property that runs a re-rendering. The code that uses this element would look like the following:
```javascript
@element('x-foo')
class XFoo extends HTMLElement {
  [propertyChangedCallback](name, oldValue, newValue) {
    if (name === 'bar') {
      this.baz = `Used new value: ${newValue}`
    }
  }

  [render]() {
    return html`
      <span>${this.baz}</span>
    `
  }
}
```
To write the implementation of the `@element` decorator I'll use the [current state](https://github.com/tc39/proposal-decorators/tree/a043d4bfff959648dceb151a1c288bb595ae2b74) of the proposal, [my suggestion](https://github.com/tc39/proposal-decorators/issues/260) of a new built-in `@inject` and permitted scoped variable creation in the decorator block. 
```javascript
import {renderer} from './renderer';

export decorator @element(name) {
  const $$invalidate = Symbol();

  @registry(target => {
    customElements.define(name, target);
  });

  @inject(function () {
    this.attachShadow({mode: 'open'});

    Object.defineProperty(this, propertyChangedCallback, {
      configurable: true,
      enumerable: true,
      value() {
        if (oldValue === newValue) {
          return;
        }

        this.constructor.prototype[propertyChangedCallback].call(this, name, oldValue, newValue);

        this[$$invalidate]();
      },
    }
  });

  @wrap(target => {
    const {connectedCallback: superConnectedCallback} = target.prototype;

    Object.defineProperty(target.prototype, 'connectedCallback', {
      configurable: true,
      enumerable: true,
      value() {
        this[$$invalidate]();
        superConnectedCallback.call(this);
      }
    });

    Object.defineProperty(target.prototype, $$invalidate, {
      configurable: true,
      enumerable: true,
      value() {
        renderer(this[render](), this.shadowRoot, this);
      }
    });
  });
}
```
So, having current set of decorators (including proposed in NEXTBUILTINS) I cannot set up the `$$invalidate` property as a private property. 

It means that we need some decorator that will be able to read, add and replace class elements as it was for class decorators in the old proposal. I'm not sure I can speak about specification right now — probably, it could be quite complex, — so let me just define the problem. 

And also let's take a look at another solution I suggest in the #263.

**Comment by littledan** [comment]
Thanks for writing up this idea and sorry for failing to get back to you on it. I can see the motivation for `@inject` and this private name API, but the current README takes a different approach. I'd appreciate feedback.
