### ISSUE TITLE
Behavior when built-in decorator is not applicable

### ISSUE THREAD

**Issue by kesne** [tc39/proposal-decorators#275]
I’m wondering what the expected behavior is when trying to apply a built-in decorator that isn’t valid where it is being used. For example, using `@expose` on a class rather than a private class element. Would this throw, or fail silently? My intuition says throw, but I also feel like this could potentially limit the ability to create highly-reusable user-defined decorators. 

Around the concern around throwing, for user-defined decorators, it’s also not immediately obvious if the decorator can be applied or not. I imagine this also gets more challenging to eyeball as more built-in decorators get added.

**Comment by littledan** [comment]
Sorry for not getting back to you on this question. I was imagining that this case would cause an early error. Anyway, we've now moved on from built-in decorators to a different form; see #310 and the README for more information. Thanks for the feedback.
