### ISSUE TITLE
@initialize's function is supposed to return undefined, but examples don't

### ISSUE THREAD

**Issue by tjcrowder** [tc39/proposal-decorators#290]
The [explainer](https://github.com/tc39/proposal-decorators) says (of `@initialize`):

> The return value is checked to be `undefined`.

But the examples use concise arrow functions that return values. Am I misreading the quote above (it *is* just after a description of how `@initialize` works when applied to the class itself or a method, but...), or is it just a small error in the examples?

If it's just a minor mistake in the examples, I'll do a PR.

Examples:

>     // set.mjs
>     export decorator @set { @initialize((instance, key, value) => instance[key] = value) }

>     // tracked.mjs
>     export decorator @tracked {
>       @initialize((instance, name, value) => instance[`__internal_${name}`] = value)
>       //...
>       })
>     }

Both of those functions return the value of `value`.

>     // bound.mjs
>     export decorator @bound {
>       @initialize((instance, name) => instance[name] = instance[name].bind(instance))
>     }

That function returns the bound function.

**Comment by nicolo-ribaudo** [comment]
Yeah, it seems like a bug in the example. The old proposal did throw an error when `initialize` returned something, and it is a check which we should keep to prevent bugs.

**Comment by littledan** [comment]
Closing per https://github.com/tc39/proposal-decorators/pull/291 . Thanks for the help here!
