### ISSUE TITLE
Differences with TypeScript decorators

### ISSUE THREAD

**Issue by legendecas** [tc39/proposal-decorators#300]
In the latest doc https://github.com/tc39/proposal-decorators/tree/691d95e67052e125239a725d2756cb8a039c5fb9#comparison-with-typescript-experimental-decorators, there is a statement that compares TypeScript ordering of decoration on an instance and a static fields with the ordering of the `@wrap` and `@register`:

> TypeScript decorators run all instance decorators before all static decorators, whereas the order of evaluation (for both `@wrap` and `@register`) in this proposal is based on the ordering in the program, regardless of whether they are static or instance.

This might not be appropriate comparison since `@wrap` and `@register` can also be applied to an instance and a static fields like TypeScript's, still there is a similar invocation ordering of `@wrap` and `@register` on the instance or static fields. Based on discussion https://github.com/tc39/proposal-decorators/issues/282#issuecomment-488627232, 

> Maybe the order should be "element wrap" -> "element register" -> "class register" -> "class wrap"?

The invocation ordering of instance decorators and static decorators of ES decorators may be identical to TypeScript decorators. But the ordering of `@wrap` and `@register` might have significant difference with TypeScript decorators.

**Comment by littledan** [comment]
We're discussing a lot of subtleties around decorators, static class fields and the mismatch with TypeScript in #329. Let's continue the discussion there.
