### ISSUE TITLE
decorators and Symbol

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-decorators#301]
![image](https://user-images.githubusercontent.com/24400797/71653714-f5afa880-2d68-11ea-87e9-ea0b10e8365f.png)

**Comment by ljharb** [comment]
I'm not sure what your question is; what's `@symbol`? Does it create two properties, `.abc` and `[Symbol('abc')]`? The comments imply that `this.abc` shouldn't work.

**Comment by 1316346949** [comment]
> I'm not sure what your question is; what's `@symbol`? Does it create two properties, `.abc` and `[Symbol('abc')]`? The comments imply that `this.abc` shouldn't work.

Sorry i think about it
