### ISSUE TITLE
Ambiguous access to 'this' for parameter decorators in EXTENSIONS.md

### ISSUE THREAD

**Issue by acutmore** [tc39/proposal-decorators#346]
Under [EXTENSIONS.md#parameter-decorators-and-annotations](https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md#parameter-decorators-and-annotations).

## 1. De-sugared code does not match text

It currently says 

> Return value: a function which takes a parameter value and returns a new parameter value. The function is called with the this value that the surrounding function is called with.

but the de-sugared code does not call the function with the surrounding this.

```js
let decInstance = dec(undefined, {kind: "parameter"});

function f(arg_) {
  const arg = decInstance(arg_); // should this be 'decInstance.call(this, arg_)' ?
  return arg * 2 ;
}
```

## 2. Unclear how `this` would work for a decorated class constructor's parameter, when the class extends another class.

```js
class Pig extends Animal {
  constructor(@verify legCount) {
    super(legCount);
  }
}
```

The above sounds like it would de-sugar to:

```js
let verifyInstance = verify(undefined, {kind: "parameter"});

class Pig extends Animal {
  constructor(legCount_) {
    let legCount = verifyInstance.call(this, legCount_); // ReferenceError: Must call super before accessing 'this'
    super(legCount);
  }
}
```

Which would throw a reference error due to accessing `this` too early. Presumably this means that when decorating a constructor parameter the behaviour would be different and `this` would be something like `globalThis` instead?

**Comment by pzuraq** [comment]
These are some interesting questions, but they're beyond the scope of this proposal. Parameter decorators are being left for a future proposal and may or may not have the exact behavior described in EXTENSIONS. The goal of EXTENSIONS is not to fully define these future proposals, but to ensure that we have left room syntactically and conceptually for them, which I believe we have. As such, I'm going to close this issue. We will address it in the future when parameter decorators are being worked on.
