### ISSUE TITLE
Update detailed semantics in the explainer

### ISSUE THREAD

**Issue by bergus** [tc39/proposal-decorators#349]
I hope I won't just get referred to the "*What would the specification look like in detail?*" FAQ entry, but reading through the [*detailed semantics* section](https://github.com/tc39/proposal-decorators/tree/a349e173c254844e6eada77199ac9ee93d30f69c#detailed-semantics) left me with a few open questions about the current proposal:

* The first concerns multiple decorators on the same element. All previous proposals did have them, and I assume they weren't dropped, ~~but none of the examples in the readme  features them. Are they still allowed?~~ (*Edit*: the [metadata example](https://github.com/tc39/proposal-decorators/tree/a349e173c254844e6eada77199ac9ee93d30f69c#decorators-adding-metadata) has two `@annotate`s). How do they work? (I have my guesses, but will wait for your response and probably open a separate issue if they don't align)
* The handling of `metadata` is not described in the detailed semantics section. I understand that this is still in flux, maybe a link to the relevant discussions could be added? What exactly does "*All of the metadata objects are Object.assign'ed together*" mean, does this deal with (recursive?) merging and getter evaluation?
* Last but not least, I don't understand the distinction between "calling" and "applying" a decorator that is made in the detailed semantics. Since the intermediate steps of the class construction are not observable anyway, how does it matter it happens in the end after the individual decorator functions are called? I agree it is important to observe that all calls are independent with no shared state being passed to them, but the actual order appears to be different from the initially mentioned steps. Especially that the class decorator functions are called after "applying" the field/method decorator functions makes this moot. I would recommend to change the description into
    1. evaluate decorator expressions to functions, in the same pass as computed property names
    2. for each field/method definition, both static and non-static, the function objects are created and passed through the respective decorator function
    3. the prototype object is put together from the non-static method/accessor elements, the constructor is put together from the field elements and static elements, the constructor and prototype are linked to each other - this step is not observable.
    4. the whole class is passed through class decorator functions. This implies access to the field metadata.

  and link the controversy #211/#329 regarding to placement of decorator calls of on `constructor`, decorator calls on `static` elements, and the actual creation (initialisation?) of static members on the class object.

**Comment by pzuraq** [comment]
I believe all of these questions have been answered in the latest versions of the README and the spec itself: https://arai-a.github.io/ecma262-compare/?pr=2417

As such I'm going to close this issue.
