### ISSUE TITLE
Is it possible to combine decorators?

### ISSUE THREAD

**Issue by willianyasim** [tc39/proposal-decorators#381]
The previous version of this specification was based on the combination of predefined decorators. It is not clear how this could be done now.

**Comment by pabloalmunia** [comment]
**The short answer is**: "yes, you can combined decorators. They are functions, and can be called without any problem".

**The extensive answer with examples**

We have a low-level decorator like this:

```js
/**
 *
 * @before(fn)
 *
 * Execute the function passed as parameter before the method, getter, setter or accessor.
 * The function passed as parameter receives all parameter passed to the target function.
 * If the function returns false, the method, getter or setter isn't called
 *
 * @param {function({array}): {void|boolean}} fn - function called before the method
 * @returns {decorator}
 *
 */
function before (fn) {
  return function (value, context) {
    
    if (['method', 'getter', 'setter'].includes (context.kind)
    ) {
      return _before(fn, value);
    }
    
    if (['init-method', 'init-getter', 'init-setter'].includes (context.kind)
    ) {
      return {
        [ context.kind === 'init-method' ?
          'method' :
          context.kind === 'init-getter' ?
            'get' :
            'set' ] : _before(fn, value)
      };
    }
    
    if (context.kind === 'auto-accessor') {
      return {
        get: _before(fn, value.get),
        set: _before(fn, value.set)
      }
    }
    
    function _before(prev, next) {
      return function (...args) {
        if (prev.call (this, args) !== false) {
          return next.call (this, ...args);
        }
      };
    }
  };
}
```

and this other

```js
/**
 *
 * @after(fn)
 *
 * Execute the function passed as parameter after the method, getter, setter or accessor call.
 * The function passed as parameter receives as parameter the previous function return.
 * If the function returns an value, this value is used as method return instead of the original return.
 *
 * @param {function({any}): {any}} fn - function called after the method
 * @returns {function}
 *
 */
module.exports = function after (fn) {
  return function (value, context) {
    
    if (['method', 'getter', 'setter'].includes (context.kind)
    ) {
      return _after(value, fn);
    }
    
    if (['init-method', 'init-getter', 'init-setter'].includes (context.kind)
    ) {
      return {
        [ context.kind === 'init-method' ?
          'method' :
          context.kind === 'init-getter' ?
            'get' :
            'set' ] : _after(value, fn)
      };
    }
    
    if (context.kind === 'auto-accessor') {
      return {
        get: _after(value.get, fn),
        set: _after(value.set, fn)
      }
    }
    
    function _after(prev, next) {
      return function (...args) {
        const result = prev.call (this, ...args)
        return next.call (this, result) ?? result
      }
    }
  };
}
```

We can use these decorators directly:

```js
class C {

  #p = 0;
  
  @before (anotherFuction)
  get p () {
    return this.#p;
  }

  @after (anotherFunction)
  set p (v) {
    return this.#p = v;
  }

}
```

and you can combine `after` and `before` into other decorator:

```js
function logger (value, context) {
  const msgAfter = (result) => console.log (context.name, 'return this value:', result);
  const msgBefore = (...args) => console.log (
    context.name,
    'is called with this parameters:',
    args.join (',') || '[]'
  );
  return after (msgAfter) (before (msgBefore) (value, context), context);
}
```

As a result, the `logger` decorator call internally to `before` and `after` decorators.

```js
class C {
  @logger
  m () {
    return 10;
  }
  @logger accessor
  p = 0;
}

const c = new C()
c.m()
c.p = 10;
console.log(c.p)
```

The complete example is https://link.javascriptdecorators.org/l7G5p3

**Comment by Jamesernator** [comment]
The above solution works for regular decorators, although it should be noted that if any decorator in a combined decorator is an `@init:` decorator, the whole decorator needs to be `@init:` as well, and you need to wire the `initialize` correctly e.g.:

```js
function combinedDecorator(value, context) {
  const { initialize: initialize1, ...rest1 } = decorator1(value, context);
  const { initialize: initialize2, ...rest2 } = decorator2(rest1, context);
  return { 
    ...rest2, 
    initialize: () => {
      initialize1();
      initialize2();
    }
  };
}
```

You would probably want to extract this sort've logic into a helper though so you can just do: `const combinedDecorator = combineDecorators(decorator1, decorator2, decorator3, ...etc);`.

**Comment by trusktr** [comment]
> The above solution works for regular decorators, although it should be noted that if any decorator in a combined decorator is an `@init:` decorator, the whole decorator needs to be `@init:` as well, and you need to wire the `initialize` correctly e.g.:

That is a rather big downside. I am with the camp that prefers `@init` to be removed and to let decorators choose what they will do internally.

I described an idea in https://github.com/tc39/proposal-decorators/issues/380#issuecomment-826361254 that shows a cleaner way to compose decorators in my opinion, and the way I see it there is no performance concern.

**Comment by Jamesernator** [comment]
> That is a rather big downside. I am with the camp that prefers @init to be removed and to let this be an internal aspect of decorators. I described an idea in #380 (comment) that shows a cleaner way to compose decorators in my opinion, and the way I see it there is no performance concern.

There's actually an [open PR](https://github.com/tc39/proposal-decorators/pull/398) now that adds `addInitializer` to the context object instead of being returned similar to your suggestion.

**Comment by trusktr** [comment]
Thanks! I saw that. I think return values could be done away with altogether.

**Comment by trusktr** [comment]
Is there a particular reason decorators have been historically designed with a return-chaining design, vs, say, and API to use within the decorators?

**Comment by Jamesernator** [comment]
> Is there a particular reason decorators have been historically designed with a return-chaining design, vs, say, and API to use within the decorators?

I dunno for the previous versions of the proposal, but I imagine the current version is so that decorators can also act as functions with minimal changes, and vice versa with higher-order-functions being used as method decorators e.g.:

```js
// simple higher-order function, can be used as decorator
function cached(func) {
  const cache = new Map();
  return function(arg) {
    if (cache.has(arg)) {
      return cache.get(arg);
    }
    const result = func(arg);
    cache.set(arg, result);
    return result;
  }
}

// simple-decorator, but can still be used as higher-order function
function logged(value, context) {
  if (context === undefined || context.type === "method") {
    return function(...args) {
      myLogger.logCall(value, args);
      return value.call(this, ...args);
    }
  } else if (context.type === "class") {
    return class extends value {
      constructor() {
        myLogger.logConstruct(value, args);
        super();
      }
    }
  } else if (context.type === "accessor") {
    return {
      get() {
        myLogger.logGet(value, this);
        return value.get.call(this);
      },
      set(newValue) {
        myLogger.logSet(value, this, newValue);
        value.set.call(this, newValue);
      },
    }
  }
  // etc
}

class Foo {
  @logged
  @cached
  foo() {}
  
  @logged
  get bar() {}
}

// Using decorators as higher order functions still works
const func = logged(cached(function() {
  console.log("Hello!");
}));
```

Admittedly I think this would be nicer with partial function application, as in practice a lot of higher order functions tend to take other arguments already anyway, e.g. for existing `cached` functions you might already accept a key func (or max size, or expiry time, or so on and so forth) e.g.:

```js
function cached(func, argsToKey=(args) => args[0]) {
  const map = new Map();
  return function(...args) {
    const key = argsToKey(args, this);
    if (map.has(key)) {
      return map.get(key);
    }
    const result = func(...args);
    map.set(key, args);
    return result;
  }
}

class Foo {
  // With partial application proposal this is still expressible, without you need to do
  // @(f => cached(f, ([x, y]) => `${ x },${ y }`))
  // which is not as great, not terrible but still less clear
  @cached(?, ([x, y]) => `${ x },${ y }`)
  doThingAtPoint(x, y) {
    return somethingAtPoint(x, y);
  }
}
```

**Comment by pzuraq** [comment]
As noted above, it is possible to combine decorators since they are just functions, so I'm going to close this issue.
