### ISSUE TITLE
Tutorial and Quick Reference

### ISSUE THREAD

**Issue by pabloalmunia** [tc39/proposal-decorators#420]
As a complement to the experimental transpiler we have prepared a small step-by-step tutorial about the current decorator specification and a quick reference:

Tutorial: https://javascriptdecorators.org/tutorial/
Quick Reference: https://javascriptdecorators.org/reference/

Any suggestions, criticisms or ideas are always welcome.

**Comment by pzuraq** [comment]
Thank you for this contribution @pabloalmunia, it was very helpful at the time! I'm going to close this issue now to clean up the issue tracker, but we definitely appreciated your exploration and support 😄
