### ISSUE TITLE
Any updates on Babel or TypeScript support? (regarding road to standardization progress)

### ISSUE THREAD

**Issue by Hawmex** [tc39/proposal-decorators#432]

**Comment by pzuraq** [comment]
The Babel plugin is a work in progress, aiming to be complete by the next TC39 meeting. TypeScript will not move forward with support until stage 3.

**Comment by thetutlage** [comment]
Waiting for the same 🙂

**Comment by nicolo-ribaudo** [comment]
Babel support has been released in v7.17.0: https://babeljs.io/blog/2022/02/02/7.17.0

**Comment by pabloalmunia** [comment]
@pzuraq and @nicolo-ribaudo congratuations, this a very important step in the decorators standardization process. At first glance the implementation seems very robust. Good work.

**Comment by pzuraq** [comment]
I'm closing this issue since I believe we've answered the question, please open a new issue if there are further concerns.

**Comment by olee** [comment]
I think this information should be included in the readme which still states that there is supposedly no babel support yet
