### ISSUE TITLE
Spec rendering broken

### ISSUE THREAD

**Issue by syg** [tc39/proposal-decorators#445]
https://arai-a.github.io/ecma262-compare/?pr=2417 isn't coming up. cc @pzuraq

**Comment by pzuraq** [comment]
@syg this is likely because I made some mistakes in the recent updates I made so the diff can't render, will fix by the end of the weekend.

**Comment by pzuraq** [comment]
I've updated the PR and all jobs are passing now, so I believe that the mistakes have been corrected, but the diff is still not updating/rendering at the moment. Maybe it's deployed every so often? Will check back tomorrow.

**Comment by pzuraq** [comment]
Looks like it's up, closing this now! Will make sure that future changes render before pushing them
