### ISSUE TITLE
Transpiler guidance section update?

### ISSUE THREAD

**Issue by thw0rted** [tc39/proposal-decorators#485]
I was reading through the proposal and noticed this in the Q&A section, under the heading addressing transpiler implementation:

> Note that this proposal is expected to continue to undergo significant changes prior to Stage 3, and it should not be counted on for stability

The proposal is now Stage 3.  Should the line be removed?  Does the guidance change now that it should be more stable?

**Comment by pzuraq** [comment]
Yes, that section should be removed and the Readme as a whole should be updated, thanks for calling that out

**Comment by pzuraq** [comment]
This will be fixed by #525
