### ISSUE TITLE
What is this in the decorator function?

### ISSUE THREAD

**Issue by pabloalmunia** [tc39/proposal-decorators#486]
Sorry if this is a stupid question, but, I try to undestand the specification and it is not clear for me. What is `this` in the decorator function? The element decorated? The decorator function?

**Comment by senocular** [comment]
`undefined`.  Search for "Call(decorator" in the [spec text](https://arai-a.github.io/ecma262-compare/?pr=2417) to see where this happens.

**Comment by pabloalmunia** [comment]
Thank you for your help.
