### ISSUE TITLE
Rename `.name`?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-decorators#495]
I’m only bringing this up because I noticed that [the API may be changed slightly](https://github.com/tc39/proposal-decorators/issues/494). That _may_ be an opportunity to also make this small improvement:

```diff
 type DecoratorContext = {
-  name: string | symbol;
+  key: string | symbol;
   // ···
 }
```

**Comment by pzuraq** [comment]
Part of the reasoning for `name` was that the human readable private name of a private field, which is not a key, is also in this field when present. The other API change also has a DX benefit, whereas this would just be updating to a new field, so I don't think this is a very well motivated change personally.
