### ISSUE TITLE
Summarize differences of this proposal vs previous versions

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-decorators#50]
Previous discussion: https://github.com/tc39/proposal-decorators-previous/issues/41

It seems especially important to note the differences vs the Babel and TypeScript decorator implementations, especially on the decorator user side.

**Comment by pzuraq** [comment]
Major differences have been summarized, I'm going to find some time to write an upgrade article to add to the repo though. Going to add a new issue for that specifically.
