### ISSUE TITLE
initializer not explained in METAPROGRAMMING.md

### ISSUE THREAD

**Issue by brad4d** [tc39/proposal-decorators#74]
Although the examples use it, the text in `METAPROGRAMMING.md` doesn't mention the `initializer` field.

**Comment by brad4d** [comment]
Also, the `get` and `set` arguments to decorator methods are not explained.
Does the class decorator also get these args, or just fields & methods?

**Comment by littledan** [comment]
Thanks for your fix. PRs are welcome to improve these explanations!

All decorators get those args. However, the API may change a bit due to https://github.com/tc39/proposal-decorators/issues/68

**Comment by littledan** [comment]
There's still lots of documentation needed, but this issue is against an older version of the proposal.
