### ISSUE TITLE
METAPROGRAMMING.md editorial comments

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-decorators#9]
1. Above the example for `defineElement` et al, you have the sentence:
    > For example, the above three decorators could be defined as follows:
    
    I think you mean for this to refer back to the examples in README.md, as they are not defined in this file.
2. The first line of the following example has:
    ```js
    import "decorators" as decorators
    ````
    I think you mean this:
    ```js
    import * as decorators from "decorators"
    ```
3. If `PrivateName` is only accessible from the `"decorators"` built-in module, then how can scripts leverage this feature?
4. In your example for `bound`, you have:
    ```js
    if (placement == "prototype") placement = "instance";
    ```
    However, in the preceding definition of a class element, you have:
    ```json
    placement: "static", "prototype", or "own",
    ``` 
5. You have the same issue as (4) in the definition of `observed`:
    ```js
    assert(placement == "instance")
    ```

**Comment by littledan** [comment]
Thanks for this report!

> If PrivateName is only accessible from the "decorators" built-in module, then how can scripts leverage this feature?

Well, they would've been able to use `import()`, but actually, the current proposal doesn't depend on modules at all, instead making `PrivateName()` a property of the global object.

**Comment by littledan** [comment]
I fixed the issues you mentioned.
